# Generated by Django 5.1.2 on 2025-03-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='com_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='telegram_username',
        ),
    ]
