# Generated by Django 5.1.2 on 2025-03-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_com_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='com_password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
