# Generated by Django 5.1.2 on 2025-03-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_com_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='br_password',
        ),
    ]
